### ISSUE TITLE
issue with uploading app to AppStore

### ISSUE THREAD

**Issue by marcinax** [Picovoice/eagle#59]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Eagle docs
- [X] I have searched the existing issues for Eagle

### SDK

iOS

### Eagle package version

1.0.0

### Framework version

Swift

### Platform

iOS

### OS/Browser version

iOS 16

### Describe the bug

I'm getting the following error when trying to upload archived app to AppStore/TestFlight. It looks like AppStore doesn't accept version number in the following form: 1.0.X which exists in the Eagle (PvEagle) framework Info.plist file.
![eagle](https://github.com/Picovoice/eagle/assets/9743434/e5bf7f59-f50b-4368-8f2e-6b6000814c48)

### Steps To Reproduce

Try to upload .ipa file of the app which has Eagle framework installed via cocoa pods.

### Expected Behavior

The version number of the PvEagle framework in the Info.plist should be changed to period-separated non-negative integers. This will allow to upload build without errors.

**Comment by ksyeo1010** [comment]
Thanks for reporting, we are working on a fix right now.

**Comment by ksyeo1010** [comment]
Issue has been fixed on https://github.com/Picovoice/eagle/pull/60. Upgrade your package to version `1.0.1` and try again.
