### ISSUE TITLE
Eagle Issue:  Failed to initialize Eagle: Profile initialization failed

### ISSUE THREAD

**Issue by mshmedlab** [Picovoice/eagle#65]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Eagle docs
- [X] I have searched the existing issues for Eagle

### SDK

Python

### Eagle package version

1.0.2

### Framework version

Python 3.8

### Platform

Linux (x86_64)

### OS/Browser version

UBNTU 20.04

### Describe the bug

I am running python3 eagle_demo_mic.py. With the following command:
 python3 eagle_demo_mic.py enroll --access_key ${ACCESS_KEY} --output_profile_path ${OUTPUT_PROFILE_PATH}
ACCESS_KEY is set to my access key
OUTPUT_PROFILE_PATH=/tmp/raz.pv
I am geeting as result:
Failed to initialize Eagle: Profile initialization failed:
  [0] Picovoice Error (code `00000136`)
  [1] Picovoice Error (code `00000136`)
  [2] Picovoice Error (code `00000136`)
  [3] Picovoice Error (code `0000012C`)
  [4] Picovoice Error (code `0000012C`)
Traceback (most recent call last):
  File "eagle_demo_mic.py", line 246, in <module>
    main()
  File "eagle_demo_mic.py", line 136, in main
    eagle_profiler = pveagle.create_profiler(
  File "/home/raz/.local/lib/python3.8/site-packages/pveagle/_factory.py", line 73, in create_profiler
    return EagleProfiler(
  File "/home/raz/.local/lib/python3.8/site-packages/pveagle/_eagle.py", line 240, in __init__
    raise _PICOVOICE_STATUS_TO_EXCEPTION[status](
pveagle._eagle.EagleActivationError: Profile initialization failed:
  [0] Picovoice Error (code `00000136`)
  [1] Picovoice Error (code `00000136`)
  [2] Picovoice Error (code `00000136`)
  [3] Picovoice Error (code `0000012C`)
  [4] Picovoice Error (code `0000012C`)

2 days ago the same command was working

### Steps To Reproduce

open terminal
cd to ~/picovoice/pveagledemo-1.0.2/pveagledemo
set ACCESS_KEY and OUTPUT_PATH
run: ~/picovoice/pveagledemo-1.0.2/pveagledemo

### Expected Behavior

Start enrolling process

**Comment by ksyeo1010** [comment]
Is your machine connected to the internet? Can you double-check your usage in https://console.picovoice.ai/?

**Comment by mshmedlab** [comment]
Hello Yeo,
I was connected to the internet and usage was few percent only. Suddenly after 15 minutes it started working.

  1.
Could you share with us the meaning of the error codes?
  2.
Note that the error was only on Eagle and Rhino was working
  3.
It's a real time system and we can afford to have it stalled, is there a way to avoid this problem. How often should it have access to the internet?
  4.
Is there a log that I can check?

Thanks for your prompt response,
Raz


[cid:cd9e9c08-5656-431b-9d0c-def9333d4577]


Mobile: +972-545234130

Email:  ***@***.***



Med Smart Hub ltd.

Yadid Ha-Kholot 3,

Zip Code 3079528,

POB 3571,

Industrial Park Caesarea,

Israel.

________________________________

**Comment by mshmedlab** [comment]
Yesterday the problem happen again with eagle.
Its the same activation key ad the Rhino, it's indicated that the network was working
The only way I was able to make it work is to disable the Eagle.
Do I need to have it connected all the time to the network.

**Comment by mrrostam** [comment]
Yes, Eagle requires an active internet connection.
