### ISSUE TITLE
Eagle Issue: 

### ISSUE THREAD

**Issue by skoky** [Picovoice/eagle#73]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Eagle docs
- [X] I have searched the existing issues for Eagle

### SDK

Python

### Eagle package version

latest

### Framework version

Rust 1.78.0

### Platform

Windows (x86_64)

### OS/Browser version

Windows or Mac

### Describe the bug

Missing Rust demo. It's is present in other models, but not in Eagle. Please add

### Steps To Reproduce

1. N/A

### Expected Behavior

Rust demo should recognize speakers from microphone

**Comment by laves** [comment]
@skoky - since you're a customer on our developer plan you can communicate with your account manager for additional feature requests + SDK support. If you encounter an actual issue with one of the existing SDKs in the repo, you can use GitHub to report it.
