### ISSUE TITLE
Enrollment speaker with audio file and recognize speaker from audio file

### ISSUE THREAD

**Issue by aidevmin** [Picovoice/eagle#81]
I read the Python SDK for speaker recognition but something was confused https://github.com/Picovoice/eagle?tab=readme-ov-file#sdks.
I have audio files of each speakers and I want to enroll these audio files (one file for each speaker). But I don't see the guide in the docs. Please add it.

For speaker recognition, I have many audio files, each file is correspond only one speaker. How to use eagle to recognize speaker from the audio file with profilers of enrollment? Because after diarization, I have many audio segments, each segment is correspond one speaker. I saw your demo, with one audio eagle outputs many value for each frame. Please correct me if I am wrong. Thank you.

**Comment by laves** [comment]
The Eagle Python API does not support file direct audio file enrolment. To enroll a speaker with one or more audio files, you need to read the audio file and pass in the raw audio data to the Eagle Profile until it has returned a signal that it has sufficient data. A demonstration of how to do this can be found in our [Eagle file demo](https://github.com/Picovoice/eagle/blob/main/demo/python/eagle_demo_file.py).

**Comment by aidevmin** [comment]
@laves 
Thank you for your response. It is more clearly after reading the source code. As my understanding we can enroll many speakers, save to the list and then we can use the profiler list for speaker recognition. 

Currently, for speaker recognition, for one audio it predicts scores and speakers for EACH frame ==> we need to do postprocess to summarize these results to identify only one speaker (one audio contains only one speaker, but contains many frames). 
I think that, you can add this feature for better usage. Many thanks.

**Comment by laves** [comment]
Glad that made it more clear. And thank you for your feedback.
